# Experiment configuration
experiment_name: "qmix_mpe_spread"
output_dir: "experiments"

# Environment configuration
environment:
  type: "mpe"
  scenario: "simple_spread"
  num_agents: 3
  max_cycles: 100

# Algorithm configuration
algorithm:
  type: "qmix"
  n_agents: 3
  obs_dim: 18
  state_dim: 54
  n_actions: 5
  hidden_dim: 64
  gamma: 0.99
  lr: 0.001
  target_update_interval: 200
  epsilon: 0.1
  buffer_size: 5000
  batch_size: 32
  min_samples: 1000

# Training configuration
training:
  max_episodes: 5000
  max_steps: 100
  eval_interval: 5000
  save_interval: 25000
  log_interval: 1000

# Logging configuration
use_wandb: true
wandb_project: "multi-agent-universal" 